const WHATSAPP_NUMBER="201283073813";let cart=JSON.parse(localStorage.getItem('mood-cart')||'[]');let activeCategory='all';
const saveCart=()=>localStorage.setItem('mood-cart',JSON.stringify(cart));
function order(name,price){window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(`عايز اطلب ${name} بسعر ${price} جنيه من كافيه مزاج`)}`,'_blank')}
function addToCart(name,price){const item=cart.find(x=>x.name===name);item?item.quantity++:cart.push({name,price,quantity:1});saveCart();updateCartUI();document.getElementById('cart-panel').classList.add('active')}
function toggleCart(){document.getElementById('cart-panel').classList.toggle('active')}
function changeQty(i,delta){cart[i].quantity+=delta;if(cart[i].quantity<1)cart.splice(i,1);saveCart();updateCartUI()}
function removeItem(i){cart.splice(i,1);saveCart();updateCartUI()}
function updateCartUI(){const box=document.getElementById('cart-items-container'),count=document.getElementById('cart-count'),total=document.getElementById('cart-total-price');count.textContent=cart.reduce((s,x)=>s+x.quantity,0);if(!cart.length){box.innerHTML='<p class="empty-cart-msg">السلة فارغة حالياً</p>';total.textContent='0';return}let sum=0;box.innerHTML=cart.map((x,i)=>{sum+=x.price*x.quantity;return `<div class="cart-item-row"><div><strong>${x.name}</strong><br><small>${x.price} ج × ${x.quantity}</small></div><div><button onclick="changeQty(${i},1)" class="btn-qty">+</button><button onclick="changeQty(${i},-1)" class="btn-qty">−</button><button onclick="removeItem(${i})" class="btn-remove">×</button></div></div>`}).join('');total.textContent=sum}
function sendWhatsAppOrder(){if(!cart.length)return alert('السلة فارغة!');let total=0;const items=cart.map(x=>{const s=x.price*x.quantity;total+=s;return `▪️ ${x.name} (الكمية: ${x.quantity}) - ${s} جنيه`}).join('\n');window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(`مرحباً، أريد طلب المنتجات التالية من كافيه مزاج:\n\n${items}\n\n💰 الإجمالي الكلي: ${total} جنيه`)}`,'_blank');const orders=JSON.parse(localStorage.getItem('mood-orders')||'[]');orders.unshift({id:'MZ-'+Date.now().toString().slice(-6),items:[...cart],total,date:new Date().toLocaleDateString('ar-EG'),status:'Pending'});localStorage.setItem('mood-orders',JSON.stringify(orders))}
function applyFilters(){const q=document.getElementById('search-input').value.trim().toLowerCase();let visible=0;document.querySelectorAll('.menu-grid .card').forEach(card=>{const match=(activeCategory==='all'||card.dataset.category===activeCategory)&&card.dataset.name.toLowerCase().includes(q);card.hidden=!match;if(match)visible++});document.getElementById('empty-state').hidden=visible!==0}
function filterMenu(){applyFilters()}
function filterCategory(category,button){activeCategory=category;document.querySelectorAll('.cat-btn').forEach(b=>b.classList.toggle('active',b===button));applyFilters()}
function openProductModal(card){const name=card.dataset.name,price=Number(card.querySelector('.price').textContent.match(/\d+/)[0]),img=card.querySelector('img').getAttribute('src'),title=card.querySelector('h3').innerHTML,desc=card.querySelector('.desc').textContent;document.getElementById('modal-product-content').innerHTML=`<div class="product-view"><img src="${img}" alt="${name}"><div class="product-info"><h2>${title}</h2><p>${desc}</p><p class="price">${price} جنيه</p><div class="modal-actions"><button class="btn" onclick="addToCart('${name}',${price});closeProductModal()">أضف للسلة</button><button class="btn btn-outline" onclick="order('${name}',${price})">واتساب</button></div></div></div>`;document.getElementById('product-modal').classList.add('open')}
function closeProductModal(){document.getElementById('product-modal').classList.remove('open')}
document.querySelectorAll('.cat-btn').forEach(btn=>btn.onclick=()=>filterCategory(btn.getAttribute('onclick').match(/'([^']+)'/)[1],btn));document.querySelectorAll('.card').forEach(card=>{card.addEventListener('dblclick',()=>openProductModal(card));card.querySelector('img').addEventListener('click',()=>openProductModal(card))});document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();document.querySelector(a.getAttribute('href'))?.scrollIntoView({behavior:'smooth'})}));document.addEventListener('mousemove',e=>{const g=document.querySelector('.cursor-glow');g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});document.getElementById('product-modal').addEventListener('click',e=>{if(e.target.id==='product-modal')closeProductModal()});updateCartUI();
