/* Zero-dependency local API + static server. Production: use a real database, HTTPS and verified Google ID tokens. */
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');const root=path.resolve(__dirname,'..'),storePath=path.join(__dirname,'data','store.json'),port=Number(process.env.PORT||8787),bootstrap=(process.env.ADMIN_BOOTSTRAP_EMAIL||'').toLowerCase();
const read=()=>JSON.parse(fs.readFileSync(storePath,'utf8'));const write=x=>fs.writeFileSync(storePath,JSON.stringify(x,null,2));const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization'});res.end(JSON.stringify(data))};const body=req=>new Promise(resolve=>{let b='';req.on('data',x=>b+=x);req.on('end',()=>{try{resolve(JSON.parse(b||'{}'))}catch{resolve({})}})});const publicUser=u=>({id:u.id,name:u.name,email:u.email,phone:u.phone,role:u.role,createdAt:u.createdAt});
function userFrom(req,db){const t=(req.headers.authorization||'').replace('Bearer ','');const s=db.sessions.find(x=>x.token===t);return s&&db.users.find(u=>u.id===s.userId)}function admin(req,db){const u=userFrom(req,db);return u&&u.role==='admin'?u:null}
http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization'});return res.end()}const url=new URL(req.url,'http://x'),p=url.pathname,db=read();if(p==='/api/health')return json(res,200,{ok:true,storage:'json'});
if(p==='/api/auth/login'&&req.method==='POST'){const x=await body(req);if(!x.email||!x.name)return json(res,400,{error:'الاسم والبريد مطلوبان'});let u=db.users.find(z=>z.email.toLowerCase()===x.email.toLowerCase());if(!u){u={id:crypto.randomUUID(),name:x.name,email:x.email.toLowerCase(),phone:x.phone||'',role:bootstrap&&x.email.toLowerCase()===bootstrap?'admin':'user',createdAt:new Date().toISOString()};db.users.push(u)}const token=crypto.randomUUID();db.sessions.push({token,userId:u.id,createdAt:new Date().toISOString()});write(db);return json(res,200,{token,user:publicUser(u)})}
if(p==='/api/auth/google'&&req.method==='POST')return json(res,501,{error:'اربط التحقق من Google ID token في server.js قبل تفعيل تسجيل Google في الإنتاج.'});
if(p==='/api/me'){const u=userFrom(req,db);return u?json(res,200,{user:publicUser(u)}):json(res,401,{error:'تسجيل الدخول مطلوب'})}
if(p==='/api/orders'&&req.method==='GET'){const u=userFrom(req,db);if(!u)return json(res,401,{error:'تسجيل الدخول مطلوب'});return json(res,200,{orders:u.role==='admin'?db.orders:db.orders.filter(o=>o.userId===u.id)})}
if(p==='/api/orders'&&req.method==='POST'){const u=userFrom(req,db),x=await body(req);if(!u)return json(res,401,{error:'تسجيل الدخول مطلوب'});const o={id:'MZ-'+Date.now().toString().slice(-6),userId:u.id,items:x.items||[],total:Number(x.total)||0,status:'Pending',createdAt:new Date().toISOString()};db.orders.unshift(o);write(db);return json(res,201,{order:o})}
if(p==='/api/admin/users'&&req.method==='GET'){if(!admin(req,db))return json(res,403,{error:'صلاحيات إدارة مطلوبة'});return json(res,200,{users:db.users.map(publicUser)})}
if(/^\/api\/admin\/users\/[^/]+\/role$/.test(p)&&req.method==='PATCH'){const a=admin(req,db),x=await body(req),id=p.split('/')[4];if(!a)return json(res,403,{error:'صلاحيات إدارة مطلوبة'});const u=db.users.find(z=>z.id===id);if(!u)return json(res,404,{error:'المستخدم غير موجود'});u.role=x.role==='admin'?'admin':'user';write(db);return json(res,200,{user:publicUser(u)})}
if(p==='/api/admin/orders'&&req.method==='GET'){if(!admin(req,db))return json(res,403,{error:'صلاحيات إدارة مطلوبة'});return json(res,200,{orders:db.orders,users:db.users.map(publicUser)})}
const file=path.normalize(path.join(root,p==='/'?'index.html':p));if(!file.startsWith(root)||!fs.existsSync(file)||fs.statSync(file).isDirectory())return res.writeHead(404).end('Not found');const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.jpg':'image/jpeg','.png':'image/png'};res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)}).listen(port,()=>console.log(`Mood server: http://localhost:${port}`));
